### ISSUE TITLE
cannot save media server

### ISSUE THREAD

**Issue by EdeAbreu23** [L4stIdi0t/arr-tools#1]
i am trying to save my connection to jellyfin but everytime i click save, it will go back to the default values

**Comment by EdeAbreu23** [comment]
i modified config.json manually and radarr and sonarr work now but mediaserver gets me this error
![image](https://github.com/user-attachments/assets/d5dc299b-89ee-4f2f-80a7-573bfd4ec360)

**Comment by mah-thingies** [comment]
@elvis0288 emby and jellyfin use the same api, you can select emby for now, ill write a fix

**Comment by EdeAbreu23** [comment]
i tried using emby but i get another error about query does not exist

![image](https://github.com/user-attachments/assets/2330c55c-a09d-405f-b48f-1ebda80b67c1)

**Comment by mah-thingies** [comment]
So, to be clear you go to the webui, you change the settings using it, you hit save, if you reboot the container does it work? because i believe that it does not hot reload the config everywhere

there should be a new update available for the container for jellyfin support

@elvis0288 
but http://jellyfin:8096/ is what you entered? could you maybe set an ip instead of docker networking thing to automatically figure out the ip? i never used that from docker and my setup can not really test it right now

ah, i get it now the UI does not save the mediaserver config

**Comment by EdeAbreu23** [comment]
so i try doing the change from the webui but it was not working i guess because i never restart the container so i went into the file and modified it directly in there.

so with your new change i get the following error and now i am using the IP
![image](https://github.com/user-attachments/assets/30790a21-4041-4a97-b27d-913697221283)

**Comment by EdeAbreu23** [comment]
looks like it is putting extra / on the IP i removed it and still the same issue
![image](https://github.com/user-attachments/assets/bc548604-af53-45f3-abc6-08f3bc6407ca)

**Comment by EdeAbreu23** [comment]
and yes, the UI is not saving the media server.. it is doing it for the sonarr and radarr.

**Comment by mah-thingies** [comment]
Well, I hoped it was  quick fix, but no. But i got to spin up jellyfin to see how they build the url because i personally added /emby/ to my url
`http://127.0.0.1:8096/emby/`
which should be added to the api in my opinion instead of users needing to add that, ill tag you when it is fixed

**Comment by EdeAbreu23** [comment]
thanks

**Comment by mah-thingies** [comment]
@elvis0288 It seems to be fixed, i tested movies on jellyfin, i did not test series so that might not yet work
and webui saving is also fixed, the new container should be available

**Comment by EdeAbreu23** [comment]
yes that fixed it. i needed to restart the docker after making the changes but it works.. i have other things i would like to mention but i will open another issue for it
