### ISSUE TITLE
dry run on tools not working

### ISSUE THREAD

**Issue by EdeAbreu23** [L4stIdi0t/arr-tools#3]
if i do a dry run on the tools i get "[ ]" but i do it on the dynaarr i will get the list of unmonitored items
![image](https://github.com/user-attachments/assets/531aff98-c90c-4741-b313-bb58cf483e1d)

**Comment by mah-thingies** [comment]
if it returns [] it means that it wants to delete nothing, "Delete unmonitored" only delete items that are unmonitored and has files

it should be more clear as well as the monitoring changes can more clearly show if it is unmonitoring or monitoring, ill improve it

**Comment by mah-thingies** [comment]
Fixed in a local commit, will be pushed later today
