### ISSUE TITLE
swipearr not optimized for web?

### ISSUE THREAD

**Issue by EdeAbreu23** [L4stIdi0t/arr-tools#4]
helllo so i see on your screenshots that swipearr looks nice and small but on my website it looks really big and i have to scroll down to see the whole thing.

![image](https://github.com/user-attachments/assets/01c97d9c-1802-406c-88b3-1f13eca4a9e8)
![image](https://github.com/user-attachments/assets/749a3293-7055-4dd0-a240-dcb0f493f87f)

**Comment by mah-thingies** [comment]
Will be fixed within a day, fastest solution is to make the width of the window smaller, but tomorrow i'll make it universal

**Comment by mah-thingies** [comment]
It is fixed in a local commit, so closing for now
there is still a bug that if the aspect ratio is wrong the youtube video can break it but i do not think many people will find that bug in normal use
(75:100 and up like 75:110, etc)

**Comment by mah-thingies** [comment]
It is fixed in a local commit, so closing for now
there is still a bug that if the aspect ratio is wrong the youtube video can break it but i do not think many people will find that bug in normal use
(75:100 and up like 75:110, etc)
