### ISSUE TITLE
question about media server?

### ISSUE THREAD

**Issue by EdeAbreu23** [L4stIdi0t/arr-tools#5]
now that the media server is working and configure, i am not sure what it is supposed to do. is there something we need to do or is this on the backend doing something?

Thanks!

**Comment by mah-thingies** [comment]
Media server does almost nothing, it is used to retrieve data for now, i want to add more features later which do use media server

for example playlist conversion(like from spotify) and creation
collections about stuff being almost deleted by decay

if you have suggestions/feature request feel free to mention them

the main features are now the swipearr and that it automatically changes quality and deletes files the dynaarr section
